#!/bin/bash


usage="
Usage: seedham [ -d ] [ -v ] [ -r arg ] [ motif_width | seed ] inputfile
Either seed or the length of seed can be given as parameter.
Input file should contain one sequence per line and nothing else.
-r arg Hamming radius
-d     Use dominance counting
-v     Be verbose"

base=$(dirname $0)

radius=1
flags="--count all"

while getopts :r:vd OPT; do
    case $OPT in
        r|+r)   # Hamming radius
            radius=$OPTARG
            ;;
        v|+v)   # verbose
            verbose=1
            ;;
        d|+d)   # dominance counting
            flags="--count neighbour"
            ;;
        *)
            #echo "usage: ${0##*/} [+-dn} [--] ARGS..."
            echo "$usage"
            exit 2
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

if [[ $# -ne 2 ]] ; then
   echo Two command line parameters are needed, $# given.
   echo "$usage"
   exit 1
fi

seed=$1
file=$2

if [[ $verbose == 1 ]] ; then
    $base/multinomial $flags --palindromic-index automatic --hamming-radius $radius $seed $file
else
    temp=$(mktemp)
    $base/multinomial $flags --palindromic-index automatic --hamming-radius $radius --output-matrix $temp $seed $file > /dev/null
    cat $temp
    rm $temp
fi
